Test, Docs: 테스트코드 작성 및 문서화#31
pre-onboarding-backend-G/feed-me-baby pull request #33
Opened 2023-11-07 14:42 UTC by hojoonSong

## PR 체크리스트
아래 항목을 확인해 주세요:

- [x] 커밋 메시지가 우리의 가이드라인을 따르고 있는지 확인하세요
- [ ] 변경 사항에 대한 테스트가 추가되었는지 확인하세요 (버그 수정 / 기능 추가)
- [ ] 문서가 추가되거나 업데이트되었는지 확인하세요 (버그 수정 / 기능 추가)

## PR 유형
이 PR은 어떤 종류의 변경을 가져오나요?

- [ ] 버그 수정
- [ ] 새로운 기능 추가
- [ ] 코드 스타일 업데이트 (서식, 로컬 변수)
- [x] 리팩터링 (기능 변경 없음, API 변경 없음)
- [ ] 빌드 관련 변경
- [ ] CI 관련 변경
- [x] 문서 내용 변경
- [ ] 애플리케이션 / 인프라 변경
- [ ] 기타... 설명:

## 관련 이슈

이슈 번호: #31

## 현재 동작은 무엇인가요?

## 새로운 동작은 무엇인가요?

## 이 PR은 호환성 변경을 도입하나요?

- [ ] 예
- [ ] 아니요

## 기타 정보

테스트 코드를 작성했습니다.
![image](https://github.com/pre-onboarding-backend-G/feed-me-baby/assets/51044545/127e476d-bf67-4e0d-8c7a-2c450e4e6320)

핵심 로직인 restaurant.service의 문서화를 진행했습니다.

2023-11-07 16:13 UTC, myeongseoklee requested changes
몇 가지 제안 남겨두었습니다!

2023-11-07 16:13 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +    await service['processSingleRestaurantData'](
private 메소드인데 테스트 코드가 작성이 가능하셨군요...? 어떻게 하셨나요

2023-11-07 16:13 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +  it('should save valid restaurant data from API and return true', async () => {
어떤 함수를 테스트하는 것인지 명시해주면 좋을 것 같습니다.

2023-11-07 16:14 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +    mockEntityManager.transaction.mockImplementation(
entityManager.transaction 메소드 내부의 콜백인 것을 확인하여 resolve 합니다.

2023-11-07 16:34 UTC, hojoonSong commented on src/restaurant/restaurant.repository.ts
> +    const cityInstance = await this.cityRepository.findOrCreate(
반영하겠습니다

2023-11-07 16:35 UTC, hojoonSong commented on src/restaurant/restaurant.service.ts
> +}
이 테스트 코드도 제작하겠습니다.

2023-11-07 16:40 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +    mockEntityManager.transaction.mockImplementation(
mockEntityManager.transaction.mockImplementation을 말하시는 거라면, 이 부분의 callback처리를 부분을 mocking을 받아서 isolationlevel 처리해주는 것으로 이해했습니다. 105번째 줄을 이야기하시는 거라면, save메소드가 repository단에서 존재하지 않아서,  save 메소드 자체를 mocking한 것입니다. 


즉 정리하자면  74번째의 mocking은 EntityManager에 대한 mocking, 105번째는 getrepository에서 받아쓰는 save메소드에 대한 transaction mocking. 109번은 isolationlevelcallback에 관한 트렌젝션 mocking이 필요한 것으로 이해했습니다.

2023-11-07 16:45 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +    await service['processSingleRestaurantData'](
JavaScript에서는 실제로 메소드에 대한 접근을 제한할 수 없고 TypeScript 컴파일러는 컴파일 시간에만 이를 강제합니다. Jest와 같은 테스팅 프레임워크를 사용할 때, TypeScript의 접근 제한자는 런타임에 적용되지 않으므로, 테스트 중인 파일이 JavaScript로 컴파일되고 나면, 실제 런타임에서는 접근 제한자가 사라지게 됩니다. 이는 테스트 코드에서 실제 클래스의 인스턴스를 사용할 때 private 메소드를 호출할 수 있게 만듭니다.

https://stackoverflow.com/questions/48906484/how-to-unit-test-private-methods-in-typescript
https://stackoverflow.com/questions/71259412/use-native-private-fields-and-methods-with-typescript-and-es5

2023-11-07 16:45 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +  it('should save valid restaurant data from API and return true', async () => {
앗 알겠씁니다.

2023-11-07 16:45 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +  it('should save valid restaurant data from API and return true', async () => {
앗 알겠씁니다.

2023-11-07 16:45 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +  it('should save valid restaurant data from API and return true', async () => {
앗 알겠습니다!

2023-11-07 16:49 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +        },
앗 답변이 날라갔네요! 

중복되는 mocking이 있는 것 같습니다. 다시 한번 확인 후에 처리해보겠습니다!

2023-11-07 17:21 UTC, hojoonSong commented on src/restaurant/restaurant.service.spec.ts
> +    await service['processSingleRestaurantData'](
라고 기술되어있는데요... 리플렉션이나 이런 용어들이 많이 나오는데, 실제론 private 함수를 테스트하지 말고, 현재의 public으로 되어있는 메소드들을 테스트하면서 private함수를 테스트한 것처럼 테스트해라~ 라는 이야기가 많긴했네요... 저는... 지금 사경을 해매서... ㅠㅠ

2023-11-08 02:30 UTC, Zamoca42 approved these changes

2023-11-08 04:45 UTC, refigo submitted a review, later dismissed

2023-11-08 06:31 UTC, myeongseoklee requested changes
간단한 수정 요청드립니다.....

2023-11-08 06:31 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +  it('TEST processSingleRestaurantData method, should increment activeCount when valid datas are provided', async () => {
1. 아래는 describe로 함수 구분해서 잘 해주신 것 같은데 여기는 it으로 구분 되어 있네요.
describe를 사용하면 테스트 코드 돌리고 터미널에 출력되는 결과에 indent가 들어가고 describe 별로 묶이기 때문에 가독성이 훨씬 좋습니다.

```typescript
// 가장 바깥에 테스트를 작성하는 클래스 또는 파일명 작성
describe ("RestaurantService" () => {
  // 그 안에는 어떤 클래스 메소드 또는 함수를 테스트하는지 함수명 작성. 함수임을 명시하기 위해 괄호도 함께 표시
  describe ("processSingleRestaurantData()", () => {
    // 테스트 케이스 별로 작성(성공, 실패 또는 엣지 케이스) 
    it ("테스트 케이스에 대한 설명", () => {
       테스트 코드 작성부분
    }
  }
}
```

2. 테스트 케이스에 대한 설명들을 혹시 한글로 작성하는 것은 어떨까요?

2023-11-08 06:31 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +  it('TEST processSingleRestaurantData method, should increment noDataCount when invalid latitude and longitude are provided', async () => {
👀

2023-11-08 06:31 UTC, myeongseoklee commented on src/restaurant/restaurant.service.spec.ts
> +  describe('validateAndFormatTelephone', () => {
👀

2023-11-08 08:35 UTC, myeongseoklee submitted a review, later dismissed
확인 완료했습니다. 고생 많으셨습니다!👍🎉

2023-11-08 09:16 UTC, Zamoca42 approved these changes
👍 고생하셨습니다!

2023-11-08 09:36 UTC, myeongseoklee approved these changes
확인 완료했습니다. 고생 많으셨습니다!👍🎉

2023-11-08 09:38 UTC, merged